#! /bin/bash
apt-get install -y git
if [[ $? -gt 0 ]]; then
	apt-get update
	apt-get install -y git
fi
git clone --recursive https://github.com/mafrosis/dotfiles.git "$HOME/dotfiles"
cd "$HOME/dotfiles" || exit 2
./install.sh zsh vim git tmux
