---
services:
  recentf1:
    image: mafrosis/recentf1
    restart: unless-stopped
    build:
      context: .
    environment:
      - DEBUG
    volumes:
      - ./listf1.py:/srv/app/listf1.py:ro
      - /media/zpool/tv/video/F1:/media:ro
