directory: /media/music

# http://beets.readthedocs.org/en/v1.3.10/plugins/replaygain.html

pluginpath: ~/.config/beets/plugins
plugins:
  - chroma
  - embedart
  - discogs
  - fetchart
  - fromfilename
  - info
  - mpdstats

match:
  preferred:
    countries: ['US', 'GB|UK']
    media: ['CD', 'Digital Media|File']
    original_year: yes

import:
  move: no      # dont move files
  copy: no      # dont copy files
  write: no     # dont write tags
  resume: yes   # resume imports
  detail: yes   # show detail of all tags
  incremental: yes  # enable incremental import
  log: /var/log/beets/import.log

paths:
  default: $genre/$albumartist - $year - $album/$track - $title
  comp: $genre/$albumartist - $year - $album/$track - $artist - $title

art_filename: folder

format_item: $artist - $album - $track - $title - $path
format_album: $albumartist - $album

# plugin settings
acoustid:
  apikey: {{ acousticid_api_key }}

chroma:
  auto: no
