#! /usr/bin/env python

from droppy.cli import entrypoint


def main():
    '''
    The main entry point for droppy CLI
    '''
    entrypoint()


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        raise SystemExit()
