#! /bin/zsh

USAGE='Usage: backup [OPTS]
  -h	display this message

  Backup d'

while getopts 'h' params
do
	case $params in
		h ) echo "$USAGE" && return 1;;
		* ) echo "$USAGE" && return 1;;
	esac
done
shift $((OPTIND-1))

##################################################

function warn {
	>&2 echo -e "\e[35m$1\e[0m"
}

function error {
	>&2 echo -e "\e[31m$1\e[0m"
}

function info {
	>&2 echo -e "\e[32m$1\e[0m"
}

##################################################

function backup {
	local backup_name=$1
	local volume_dir=$2

	echo docker run --rm -it \
		-v ${volume_dir}:/backup \
		-v /home/mafro/.config/kopia/mafro-backup-7deca97f9b3e.json:/gcs.json:ro \
		-e KOPIA_PASSWORD \
		-w /backup \
		--hostname=${backup_name} \
		mafrosis/kopia snapshot create
}

##################################################

function main {
	if [[ -f /etc/kopia.conf && -r /etc/kopia.conf ]]; then
		source /etc/kopia.conf
	else
		warn 'Missing or unreadable /etc/kopia.conf'
	fi

	if [[ -z KOPIA_PASSWORD ]]; then
		error 'KOPIA_PASSWORD is not set'
		return 2
	fi

	# Iterate docker volumes
	docker volume ls --format "{{.Name}}\t{{.Mountpoint}}" | while IFS=$'\t' read -r volume_name mount_point; do
		if docker volume inspect $volume_name | grep -q 'net.mafro.kopia'; then
			backup $volume_name $mount_point
		fi
	done
}
main; return $?
