#! /bin/bash

if command -v terminal-notifier >/dev/null 2>&1; then
	terminal-notifier \
		-title "${2:-terminal}" \
		-message "${1:-Done}" \
		-open "file://${3:-}"

elif [[ ! -z $TMUX ]]; then
	tmux_window=$(/usr/bin/tmux list-windows \
		-F "#{window_active} #{window_index} #{window_name}" | \
		sort | tail -n 1 | cut -d ' ' -f 2-)
	notification="$1 in ${tmux_window}"
	tmux display-message "${notification}"

fi
