#! /bin/zsh

USAGE='Usage: f [OPTS] SUFFIX [SEARCHSTR]
  -a	audio quality [0-100]

  Supply a SUFFIX to find for specific filetypes
  Specify . as SUFFIX to find all filetypes
  Specify SEARCHSTR to filter results for only files including SEARCHSTR
  '

if [ $# -eq 0 ]; then
	return 1

elif [ $# -eq 1 ]; then
	find . -type f -name "*.$1"

elif [ $# -eq 2 ]; then
	if [ "$1" = '.' ]; then
		find . -type f \
			-not -path '*/\.*' \
			-not -path '*/node_modules*' \
			-not -path '*/venv*' \
			-print0 | \
			xargs -0 grep --color=always -n -- "$2"
	else
		find . -type f \
			-not -path '*/\.*' \
			-not -path '*/node_modules*' \
			-not -path '*/venv*' \
			-name "*.$1" \
			-print0 | \
			xargs -0 grep --color=always -n -- "$2"
	fi
fi
