#! /bin/zsh

if [ $# -eq 0 ]; then
	echo 'Usage: f <suffix> [search-str]'
	echo "  Supplying '.' as <suffix> will search all files"
	return 1

elif [ $# -eq 1 ]; then
	find . -type f -name "*.$1"

elif [ $# -eq 2 ]; then
	if [ "$1" = '.' ]; then
		find . -type f -not -path '*/\.*' -print0 | xargs -0 grep --color=always -n -- "$2"
	else
		find . -type f -not -path '*/\.*' -name "*.$1" -print0 | xargs -0 grep --color=always -n -- "$2"
	fi
fi
