#! /bin/zsh

python3 -m venv venv
source venv/bin/activate
python3 -m pip install --upgrade pip

if [[ -f pyproject.toml ]]; then
	pip install -e .
elif [[ -f requirements.txt ]]; then
	pip install -r requirements.txt
fi
