#!/bin/zsh

function cleanup {
	rm -rf ${TMPDIR}
}
trap cleanup EXIT

# Ensure cookiecutter
if ! command -v cookiecutter &> /dev/null; then
	pipx install cookiecutter
fi

# Support targeting an existing directory
if [[ -d ${1:h} && ${1:h} != '.' ]]; then
	OUTPUT_DIR=${1:h}
else
	OUTPUT_DIR=$(pwd)
fi

# Create temporary directory
TMPDIR=$(mktemp -d)

git clone -q https://github.com/mafrosis/pytemplate.git ${TMPDIR}/pytemplate
pushd ${TMPDIR}/pytemplate

cookiecutter --no-input . project_name=${1:t}

mv ${1:t} ${OUTPUT_DIR}

popd
