#! /bin/zsh

USAGE='Usage: vagrant-cleanup [-D]
  -D delete an orphaned machines'

DELETE=0

while getopts 'D' params
do
	case $params in
		D ) DELETE=1;;
		\? ) echo $USAGE
			 return 1;;
		* ) echo $USAGE
			return 1;;
	esac
done
shift $(($OPTIND-1))


typeset -a MACHINES
typeset -a VAGRANTS

for M in ~/.vagrant.d/machines/*; do
	MACHINES+=(${M[34,69]})
done

find ~ -type d -name .vagrant | while read D; do
	if [[ -f $D/machines/default/vmware_fusion/id ]]; then
		VMFILE=$(cat $D/machines/default/vmware_fusion/id)
		UUID=${VMFILE[34,69]}
		VAGRANTS+=($UUID)

		if [[ ${MACHINES[(r)$UUID]} == $UUID ]]; then
			echo "Machine $UUID found at $D"
		fi
	fi
done

for M in $VAGRANTS; do
	if [[ ${MACHINES[(r)$M]} == $M ]]; then
		if [[ $DELETE -eq 1 ]]; then
			SIZE=$(du -h -d 1 ~/.vagrant.d/machines/$M | awk '{print $1}')
			rm -rf ~/.vagrant.d/machines/$M
			echo "Machine $M deleted freeing $SIZE"
		else
			echo "Machine $M has been orphaned!"
		fi
	fi
done
