#! /bin/zsh

if [[ -x /usr/local/bin/wakeonlan ]]; then
	WOLBIN=/usr/local/bin/wakeonlan
elif [[ -x /usr/bin/wakeonlan ]]; then
	WOLBIN=/usr/bin/wakeonlan
elif [[ -x /bin/wakeonlan ]]; then
	WOLBIN=/bin/wakeonlan
elif [[ -x /opt/homebrew/bin/wakeonlan ]]; then
	WOLBIN=/opt/homebrew/bin/wakeonlan
else
	echo 'wakeonlan: not found'
	return 1
fi

if [[ -f ~/.wakeonlan/$1 ]]; then
	$WOLBIN -f ~/.wakeonlan/$1
else
	$WOLBIN $@
fi
